### PR TITLE
change verbosity level to normal

### PR DESCRIPTION
**Pull request by deronnax**
So I had the confirmation in [pdm#2460](https://github.com/pdm-project/pdm/pull/2460) that the verbosity level is actually normal, so it's up to pdm-dotenv to change its verbosity level. With this change, the message still shows up on normal invocation and doesn't when `--quiet` is passed to pdm:

```
➜  pdm venv activate
Loading dotenv file /Users/mathieu/dev/pdm-dotenv/.env
source '/Users/mathieu/Library/Application Support/pdm/venvs/pdm-dotenv-LmuwbYeK-3.10/bin/activate'
➜  pdm venv activate --quiet
source '/Users/mathieu/Library/Application Support/pdm/venvs/pdm-dotenv-LmuwbYeK-3.10/bin/activate'
```

### CODE REVIEW

**Comment by znd4** [comment]
This looks great; thanks for taking the time to track this down :)

I'm gonna spend some time today trying to add some tests for this, including a bit a of refactoring, but if I haven't merged this PR by later in the week, feel free to nudge me here and I'll merge and release without them b.c. the downside risk of this change seems pretty small

**Comment by deronnax** [comment]
Cool. Thank you.

**Comment by deronnax** [comment]
Hey, it's actually causing some problems for us, it would be super nice if our devs could already use it. Would you please merge it and release, even it not covered by tests?

**Review by znd4 — APPROVED** [review]
sorry, just saw your latest comment earlier tonight!

`--quiet` doesn't seem to work right after `pdm` (at least as I'd expect), although it works after the subcommand.

That being said, I just saw that there's an option to output to `stderr` instead of `stdout`, which should hopefully fix `pdm venv activate`. In case it doesn't, `pdm venv --quiet activate` should work now

**Comment by deronnax** [comment]
I take note. Thank you very much for the merge 🙇

**Pull request merged**
